// Generated by Bun plugin at 3/7/2024, 9:26:05 PM

declare namespace NodeJS {
    export interface ProcessEnv {
		IGNORED_VAR: string;
		VALID_VAR: string;
		TEST_VAR: string;
		LOCAL_VAR: string;
		EXAMPLE_VAR: string;
    }
}


//---------------------------------------------------------------------//
//-----------------------ADD YOUR CODE BELOW---------------------------//
//---------------------------------------------------------------------//

